### ISSUE TITLE
Inconsistent sent time, delivery time not updating

### ISSUE THREAD

**Issue by Zokii0** [dekusms/DekuSMS-Android#418]
When I click message details, sent time is shown very random and wrong: 

![Image](https://github.com/user-attachments/assets/2d88d4c9-43a9-40df-964e-6af757de4eae)

![Image](https://github.com/user-attachments/assets/a5a52f4d-6f32-47c7-8d1d-e2c09b0bb197)

![Image](https://github.com/user-attachments/assets/cb359a67-a97d-4e79-a1a4-d1c55f2a0a42)

Also delivery time isn't updated when I tested with other device by turning airplane mode on and off few minutes later (if it was supposed to be shown under message where is actually shown right sent time, instead of in message details?)

**Comment by sherlockwisdom** [comment]
Should be fixed in latest release

**Comment by Zokii0** [comment]
So when can we test it? 👀

**Comment by Zokii0** [comment]
Hello, this issue still occurs after latest updated from F-Droid 0.75.0
